// Generated by itsjason
// import 'package:flutter/material.dart';

class Room {

  String id;
	String name;
	DateTime createdAt;
	String ownerId;
	List<String> users;

	Room({this.name, this.createdAt, this.ownerId, this.users});

  Room.fromMap(String id, Map<dynamic, dynamic> map)
      : id = id,
      name = map['name'],
			createdAt = map['createdAt'],
			ownerId = map['ownerId'],
			users = map['users'];

  Map<String, dynamic> toMap() => {
    "id": this.id, 
    "name": this.name,
		"createdAt": this.createdAt,
		"ownerId": this.ownerId,
		"users": this.users  };

  @override
  String toString() => "Room<id:$id>";
}
    